spring:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*spring*/**'
          - '**/*Spring*/**'
          - '**/*batch*/**'
          - '**/*jpa*/**'

redis:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*redis*/**'
          - '**/*Redis*/**'
          - '**/*cache*/**'

kafka:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*kafka*/**'
          - '**/*Kafka*/**'
          - '**/*message*/**'

database:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*mysql*/**'
          - '**/*postgresql*/**'
          - '**/*db*/**'
          - '**/*sql*/**'

devops:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*docker*/**'
          - '**/*k8s*/**'
          - '**/*kubernetes*/**'
          - '**/*aws*/**'